spring:
  application:
    name: auth-app

  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: root
    password: ${DB_PASSWORD:vedant@555}
    driver-class-name: com.mysql.cj.jdbc.Driver

  #   Learn and Read this properties
  #   hikari:
  #     pool-name: HikariCP
  #     maximum-pool-size: 5
  #     connection-timeout: 30000
  #     idle-timeout: 600000
  #     max-lifetime: 1800000
  #     validation-timeout: 5000
  #     leak-detection-threshold: 0
  #     initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # dialect can be removed

server:
  # port: 8555
  error:
    include-message: always

security:
  jwt:
    secret: aBcDeFgHiJkLmNoPqRsTuVwXyZ1234567890aBcDeFgHiJkLmNoPqRsTuVwXyZ12
    issuer: api.substring.com
    access-ttl-seconds: 3600
    refresh-ttl-seconds: 86400
    refresh-token-cookie-name: refreshToken
    cookie-secure: true
    cookie-same-site: lax

