spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:8181/realms/fitness-oauth2/protocol/openid-connect/certs
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888