spring.application.name=SpringOauth2Demo
server.port=8000

spring.security.oauth2.client.registration.google.client-id= 698250011644-bagospblnvo4gn58o4rvhpgq7kcbtme2.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secrete= 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



# client id:  698250011644-bagospblnvo4gn58o4rvhpgq7kcbtme2.apps.googleusercontent.com
# client secrete: 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