# Server port
server.port=8080

# PostgreSQL Database Settings
spring.datasource.url=jdbc:postgresql://db.ewkjdqmtqypgmfbonnqg.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=vedant93701154
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Supabase JWT Auth Settings
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://ewkjdqmtqypgmfbonnqg.supabase.co/auth/v1
